name: SORACOM Orbit CI/CD

on:
  push:
    branches: [ master, staging]
  workflow_dispatch:

env:
  SORALET_ID: discovery2023-demo
  COVERAGE: jp
  SORACOM_GROUP_ID_STG: c3b887a0-d352-4340-b4d7-ba385d358fb1
  SORACOM_GROUP_ID_PROD: 3597a061-d7ad-4198-8b8f-b8f1d4ab8c75
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kenichiro-kimura/orbit-assemblyscript:latest
      options: --cpus 1
      credentials:
        username: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
        password: ${{ secrets.GHCR_CONTAINER_REGISTRY_PASSWORD }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: initialize
        run: npm run init
      - name: copy libs
        run: cp -r /workspaces/orbit-sdk-assemblyscript ../
      - name: build
        run: npm run build
      - name: build optimized
        run: npm run build:optimized
      - name: test
        run: npm run test -- -u
      - name: upload assets
        uses: actions/upload-artifact@v2
        with:
          name: soracom-orbit
          path: build/soralet-optimized.wasm

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: soracom-orbit
      - name: upload
        uses: kenichiro-kimura/action-soracom-upload-soralet@1.2.0
        id: upload
        with:
          soracom_auth_key: ${{ secrets.AUTH_KEY }}
          soracom_auth_key_id: ${{ secrets.AUTH_KEY_ID}}
          soracom_coverage: ${{ env.COVERAGE }}
          soracom_soralet_id: ${{ env.SORALET_ID }}
          soracom_soralet_filename: soralet-optimized.wasm
          soracom_delete_old_soralet: true
      - name: deploy staging
        uses: kenichiro-kimura/action-soracom-configure-orbit@1.0.1
        if: github.ref == 'refs/heads/staging'
        with:
          soracom_auth_key: ${{ secrets.AUTH_KEY }}
          soracom_auth_key_id: ${{ secrets.AUTH_KEY_ID}}
          soracom_coverage: ${{ env.COVERAGE }}
          soracom_soralet_code_srn: ${{ steps.upload.outputs.soralet_srn }}
          soracom_soralet_direction: uplink
          soracom_group_id: ${{ env.SORACOM_GROUP_ID_STG }}
          soracom_soralet_enable: true
      - name: deploy production
        uses: kenichiro-kimura/action-soracom-configure-orbit@1.0.1
        if: github.ref == 'refs/heads/master'
        with:
          soracom_auth_key: ${{ secrets.AUTH_KEY }}
          soracom_auth_key_id: ${{ secrets.AUTH_KEY_ID}}
          soracom_coverage: ${{ env.COVERAGE }}
          soracom_soralet_code_srn: ${{ steps.upload.outputs.soralet_srn }}
          soracom_soralet_direction: uplink
          soracom_group_id: ${{ env.SORACOM_GROUP_ID_PROD }}
          soracom_soralet_enable: true
